### ISSUE TITLE
SMS does not contain expected text

### ISSUE THREAD

**Issue by mcf-rocks** [messagebird/sachet#100]
I have this in the alert rules:
```    - alert: DiskDevice
      expr: node_disk_device_size_used_perc > 60
      for: 1m
      labels:
        severity: "warning"
      annotations:
        description: "Disk device {{ $labels.device }} on {{ $labels.instance }} at {{ $value }}% used"
```
What I get in my text message is:
```
FIRING
device=/dev/sda1
instance=bababoom
job=bababoomjob
severitywarning
```
I would like the text to contain the description -- do you know how ot do it?

**Comment by mcf-rocks** [comment]
I also tried like this
```
rules:
      labels:
        severity: "warning"
        text: "Disk device {{ $labels.device }} on {{ $labels.instance }} at {{ $value }}% used"
```
and
```
sachet.yaml:
    text: '{{ .Labels.text }}'
```
Now I don't even get the text.
